In [1]:
pip install numpy

In [141]:
import numpy as np

In [3]:
my_list={1, 2, 3, 4,5}
my_array=np.array(my_list)
print(my_array)

{1, 2, 3, 4, 5}


built in functions

In [ ]:
abc=np.zeros(10)

In [5]:
abc

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
ones= np.ones(3)

In [14]:
ones

array([1., 1., 1.])

MATRICES

In [16]:
identity_matrix=np.eye(5)#creates identity matrix
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
ra=np.arange(1, 10, 2)#creates an array from 1 to 9 with a step of 2
ra

array([1, 3, 5, 7, 9])

In [22]:
np.linspace(0,1,5)#creates 5 even ly spaced valus btw 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.random.rand(2,2)

array([[0.13466056, 0.01061103],
       [0.74738105, 0.04420928]])

ACCESSING AND SLICING AN ARRAY

In [46]:
my_list=[[1,2.7,3,4,5],[6,7,8,9,10]]

In [48]:
my_array=np.array(my_list)

In [50]:
my_array

array([[ 1. ,  2.7,  3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ,  9. , 10. ]])

In [52]:
my_array[0][0:4]

array([1. , 2.7, 3. , 4. ])

ARRAY PROPERTIES

In [55]:
my_array.shape

(2, 5)

In [57]:
my_array.dtype

dtype('float64')

In [59]:
a1=[1,2,3]
a2=[2,3,4]

RESHAPING

In [73]:
l1=[1,2.7,3,4,5]

In [106]:
#reshape=l1.reshape(2,3)

STACKING ARRAYS

In [109]:
a1=np.array([1,2,3])
a2=np.array([3,4,5])

In [111]:
stack_vert=np.vstack((a1,a2))

In [113]:
stack_vert


array([[1, 2, 3],
       [3, 4, 5]])

SORTING ARRAYS

In [116]:
original=np.array([3,1,2,4,5])
sorted=np.sort(original)

In [118]:
sorted

array([1, 2, 3, 4, 5])

In [120]:
decend=np.sort(original[::-1])

In [134]:
decend

array([1, 2, 3, 4, 5])